insert into Record (TrackID, Artist, Track, Price, Artwork, Audio)values ('2013',	'Dino',	'Roar',	9.99,	'Dino.jpg',	'Dino - Roar.mp3'),
('2014',	'Ernie And The Berts',	'Ruy De Sesame',	9.99,	'Ernie.jpg',	'Ernie And The Berts - Ruy De Sesame.mp3'),
('2015',	'Fighting Badgers',	'Come At Me',	9.99,	'fight.png',	'Fighting Badgers - Come At Me.MP3'),
('2016',	'Gonatozygon',	'Growing Up',	9.99,	'Gonatozygon.png',	'Gonatozygon - Growing Up.mp3'),
('2017',	'Halifax',	'Armada',	9.99,	'Halifax1.png',	'Halifax - Armada.mp3'),
('2018',	'Halifax',	'Poured Lines',	9.99,	'Halifax2.png',	'Halifax - Poured Lines.mp3'),
('2019',	'Hudson',	'Crossed Paths',	9.99,	'Hudson.png',	'Hudson - Crossed Paths.mp3'),
('2020',	'Infinity Mirror',	'Lone Egret',	9.99,	'Infinity.jpg',	'Infinity Mirror - Lone Egret.mp3'),
('2021',	'Jane Doe',	'Freedom',	9.99,	'Jane.jpg',	'Jane Doe - Freedom.mp3'),
('2022',	'Jeb',	'Jeb',	9.99,	'Jeb.jpg',	'Jeb - Jeb.mp3'),
('2023',	'Kobogo',	'A Bugs Life',	9.99,	'Kobogo.jpg',	'Kobogo - A Bugs Life.MP3'),
('2024',	'Kobogo',	'Never Blend In',	9.99,	'Kobogo2.jpg',	'Kobogo - Never Blend In.mp3'),
('2025',	'Legacy Systems',	'Hell On Earth',	9.99,	'LegacyHell.png',	'Legacy Systems - Hell On Earth.mp3'),
('2026',	'Legacy Systems',	'How Do I Delete This',	9.99,	'LegacyHow.jpg',	'Legacy Systems - How Do I Delete This.mp3'),
('2027',	'Legacy Systems',	'Out Of Date',	9.99,	'LegacyOut.png',	'Legacy Systems - Out Of Date.mp3'),
('2028',	'Legacy Systems',	'These Men Are Not Friends',	9.99,	'LegacyFriends.jpg',	'Legacy Systems - These Men Are Not Friends.mp3'),
('2029',	'Life Arctic',	'Noise',	9.99,	'Life.png',	'Life Arctic - Noise.mp3'),
('2030',	'Lo-Fi Sunrise',	'Video',	9.99,	'Lo-Fi.png',	'Lo-Fi Sunrise - Video.mp3'),
('2031',	'Nebula',	'I Dont Care',	9.99,	'NebulaI.jpg',	'Nebula - I Dont Care.mp3'),
('2032',	'Nebula',	'Nebula',	9.99,	'Nebula.jpg',	'Nebula - Nebula.mp3'),
('2033',	'Night Terrors',	'Down',	9.99,	'Night.png',	'Night Terrors - Down.mp3'),
('2034',	'Nostromo',	'Arrival',	9.99,	'NostromoArrival.jpg',	'Nostromo - Arrival.mp3'),
('2035',	'Nostromo',	'Contact',	9.99,	'NostromoContact.jpg',	'Nostromo - Contact.mp3'),
('2036',	'Nostromo',	'Countdown',	9.99,	'NostromoCountdown.jpg',	'Nostromo - Countdown.mp3'),
('2037',	'O Douglas',	'Taste',	9.99,	'ODouglas.png',	'O Douglas - Taste.mp3'),
('2038',	'Perspective Error',	'Fun Things Are Fun',	9.99,	'Perspective.png',	'Perspective Error - Fun Things Are Fun.mp3'),
('2039',	'QR',	'Code',	9.99,	'QR.jpg',	'QR - Code.mp3'),
('2040',	'Quiche',	'Midnight Quiche',	9.99,	'Quiche.jpg',	'Quiche - Midnight Quiche.mp3'),
('2041',	'Rebekkah',	'Modern Venus',	9.99,	'Rebekkah.png',	'Rebekkah - Modern Venus.mp3'),
('2042',	'Right Hand Man',	'Sauce',	9.99,	'Right.jpg',	'Right Hand Man - Sauce.mp3'),
('2043',	'Rose',	'Scene',	9.99,	'Rose.jpg',	'Rose - Scene.mp3'),
('2044',	'Sama',	'The Cost Of High Living',	9.99,	'Sama.png',	'Sama - The Cost of High Living.mp3'),
('2045',	'Sojourn',	'Moon',	9.99,	'SojournMoon.jpg',	'Sojourn - Moon.mp3'),
('2046',	'Sojourn',	'Ocean',	9.99,	'SojournOcean.jpg',	'Sojourn - Ocean.mp3'),
('2047',	'System',	'Collision',	9.99,	'SystemCollision.jpg',	'System - Collision.mp3'),
('2048',	'The Auditions',	'Camouflage',	9.99,	'TheAuditions.jpg',	'The Auditions - Camouflage.mp3'),
('2049',	'Tokyo Girl',	'C.A.',	9.99,	'Tokyo.jpg',	'Tokyo Girl - C.A..mp3'),
('2050',	'Tower',	'Tower',	9.99,	'Tower.png',	'Tower - Tower.mp3'),
('2051',	'Trams',	'Moshi Moshi',	9.99,	'Trams.png',	'Trams - Moshi Moshi.mp3'),
('2052',	'Travis Lee',	'Saints & Sinners',	9.99,	'Travis.jpg',	'Travis Lee - Saints & Sinners.mp3'),
('2053',	'Unacceptable Use',	'Right Side Up',	9.99,	'Unacceptable.jpg',	'Unacceptable Use - Right Side Up.mp3'),
('2054',	'Universal Robots',	'Goodbye',	9.99,	'Universal.jpg',	'Universal Robots - Goodbye.mp3'),
('2055',	'Virgin',	'Virgin',	9.99,	'Virgin.jpg',	'Virgin - Virgin.mp3'),
('2054',	'Wilson',	'LightHouse',	9.99,	'Wilson.jpg',	'Wilson - LightHouse.mp3')
